add_test( [==[Alu - AddBasic]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[Alu - AddBasic]==]  )
set_tests_properties( [==[Alu - AddBasic]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[Alu - AddZero]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[Alu - AddZero]==]  )
set_tests_properties( [==[Alu - AddZero]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[Alu - AddCarry]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[Alu - AddCarry]==]  )
set_tests_properties( [==[Alu - AddCarry]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[Alu - SubBorrow]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[Alu - SubBorrow]==]  )
set_tests_properties( [==[Alu - SubBorrow]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[Alu - SignedOverflow]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[Alu - SignedOverflow]==]  )
set_tests_properties( [==[Alu - SignedOverflow]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[Lexer - Tokenize Simple Instruction]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[Lexer - Tokenize Simple Instruction]==]  )
set_tests_properties( [==[Lexer - Tokenize Simple Instruction]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[Lexer - Tokenize Immediate Values]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[Lexer - Tokenize Immediate Values]==]  )
set_tests_properties( [==[Lexer - Tokenize Immediate Values]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[Lexer - Labels and Directives]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[Lexer - Labels and Directives]==]  )
set_tests_properties( [==[Lexer - Labels and Directives]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[Lexer - Comments and Whitespace]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[Lexer - Comments and Whitespace]==]  )
set_tests_properties( [==[Lexer - Comments and Whitespace]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[Lexer - Brackets (Memory Access)]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[Lexer - Brackets (Memory Access)]==]  )
set_tests_properties( [==[Lexer - Brackets (Memory Access)]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[Lexer - Features: Bin, Neg, Strings]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[Lexer - Features: Bin\, Neg\, Strings]==]  )
set_tests_properties( [==[Lexer - Features: Bin, Neg, Strings]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[Lexer - High Registers]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[Lexer - High Registers]==]  )
set_tests_properties( [==[Lexer - High Registers]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[Bus - AddressDecoding]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[Bus - AddressDecoding]==]  )
set_tests_properties( [==[Bus - AddressDecoding]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[Bus - ReadOperation]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[Bus - ReadOperation]==]  )
set_tests_properties( [==[Bus - ReadOperation]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[Bus - BusFault]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[Bus - BusFault]==]  )
set_tests_properties( [==[Bus - BusFault]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[NvmeController - WriteAndReadBasic]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[NvmeController - WriteAndReadBasic]==]  )
set_tests_properties( [==[NvmeController - WriteAndReadBasic]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[BitManip - SetBit]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[BitManip - SetBit]==]  )
set_tests_properties( [==[BitManip - SetBit]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[BitManip - CheckBit]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[BitManip - CheckBit]==]  )
set_tests_properties( [==[BitManip - CheckBit]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[BitManip - ExtractBits]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[BitManip - ExtractBits]==]  )
set_tests_properties( [==[BitManip - ExtractBits]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[CpuPipeline - ExecuteADD]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[CpuPipeline - ExecuteADD]==]  )
set_tests_properties( [==[CpuPipeline - ExecuteADD]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[CpuPipeline - ExecuteBranch]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[CpuPipeline - ExecuteBranch]==]  )
set_tests_properties( [==[CpuPipeline - ExecuteBranch]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[CpuPipeline - ExecuteLDR]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[CpuPipeline - ExecuteLDR]==]  )
set_tests_properties( [==[CpuPipeline - ExecuteLDR]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[Cpu - InitialState]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[Cpu - InitialState]==]  )
set_tests_properties( [==[Cpu - InitialState]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[Cpu - ResetBehavior]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[Cpu - ResetBehavior]==]  )
set_tests_properties( [==[Cpu - ResetBehavior]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[Cpu - RegisterAccess]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[Cpu - RegisterAccess]==]  )
set_tests_properties( [==[Cpu - RegisterAccess]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[Decoder - DecodeRegisterArithmetic]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[Decoder - DecodeRegisterArithmetic]==]  )
set_tests_properties( [==[Decoder - DecodeRegisterArithmetic]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[Decoder - DecodeImmediateMove]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[Decoder - DecodeImmediateMove]==]  )
set_tests_properties( [==[Decoder - DecodeImmediateMove]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[Decoder - DecodeBranch]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[Decoder - DecodeBranch]==]  )
set_tests_properties( [==[Decoder - DecodeBranch]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[Encoder - Data Processing]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[Encoder - Data Processing]==]  )
set_tests_properties( [==[Encoder - Data Processing]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[Encoder - Immediate Operation]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[Encoder - Immediate Operation]==]  )
set_tests_properties( [==[Encoder - Immediate Operation]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[Encoder - Memory Operation]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[Encoder - Memory Operation]==]  )
set_tests_properties( [==[Encoder - Memory Operation]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[Encoder - Branch Resolved]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[Encoder - Branch Resolved]==]  )
set_tests_properties( [==[Encoder - Branch Resolved]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[Encoder - Validation: Wrong Operand Count]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[Encoder - Validation: Wrong Operand Count]==]  )
set_tests_properties( [==[Encoder - Validation: Wrong Operand Count]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[Encoder - Validation: Wrong Operand Type]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[Encoder - Validation: Wrong Operand Type]==]  )
set_tests_properties( [==[Encoder - Validation: Wrong Operand Type]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[Encoder - Validation: Immediate Out of Range]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[Encoder - Validation: Immediate Out of Range]==]  )
set_tests_properties( [==[Encoder - Validation: Immediate Out of Range]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[Encoder - Validation: Memory Operation Wrong Type]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[Encoder - Validation: Memory Operation Wrong Type]==]  )
set_tests_properties( [==[Encoder - Validation: Memory Operation Wrong Type]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[Encoder - Validation: Branch with Register]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[Encoder - Validation: Branch with Register]==]  )
set_tests_properties( [==[Encoder - Validation: Branch with Register]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[Encoder - Validation: NOP with Operands]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[Encoder - Validation: NOP with Operands]==]  )
set_tests_properties( [==[Encoder - Validation: NOP with Operands]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[Encoder - Validation: CMP Uses Rn Not Rd]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[Encoder - Validation: CMP Uses Rn Not Rd]==]  )
set_tests_properties( [==[Encoder - Validation: CMP Uses Rn Not Rd]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[FTL - Persistence Rebuild]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[FTL - Persistence Rebuild]==]  )
set_tests_properties( [==[FTL - Persistence Rebuild]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[FTL - BlockTransitionAndAllocation]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[FTL - BlockTransitionAndAllocation]==]  )
set_tests_properties( [==[FTL - BlockTransitionAndAllocation]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[FTL - DeviceFullBehavior]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[FTL - DeviceFullBehavior]==]  )
set_tests_properties( [==[FTL - DeviceFullBehavior]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[FTL - GarbageCollection_ReclaimsSpace]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[FTL - GarbageCollection_ReclaimsSpace]==]  )
set_tests_properties( [==[FTL - GarbageCollection_ReclaimsSpace]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[Memory - StorageAccess]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[Memory - StorageAccess]==]  )
set_tests_properties( [==[Memory - StorageAccess]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[Memory - LatencySimulation]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[Memory - LatencySimulation]==]  )
set_tests_properties( [==[Memory - LatencySimulation]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[Nand - InitialStateIsErased]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[Nand - InitialStateIsErased]==]  )
set_tests_properties( [==[Nand - InitialStateIsErased]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[Nand - ProgramSuccess]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[Nand - ProgramSuccess]==]  )
set_tests_properties( [==[Nand - ProgramSuccess]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[Nand - ProgramFailure_BitFlipConstraint]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[Nand - ProgramFailure_BitFlipConstraint]==]  )
set_tests_properties( [==[Nand - ProgramFailure_BitFlipConstraint]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[Nand - EraseRecover]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[Nand - EraseRecover]==]  )
set_tests_properties( [==[Nand - EraseRecover]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[Parser - Instruction Parsing]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[Parser - Instruction Parsing]==]  )
set_tests_properties( [==[Parser - Instruction Parsing]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[Parser - Immediate and Aliases]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[Parser - Immediate and Aliases]==]  )
set_tests_properties( [==[Parser - Immediate and Aliases]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[Parser - Memory Operand]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[Parser - Memory Operand]==]  )
set_tests_properties( [==[Parser - Memory Operand]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[Parser - String Directive]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[Parser - String Directive]==]  )
set_tests_properties( [==[Parser - String Directive]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[Parser - Error Reporting]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[Parser - Error Reporting]==]  )
set_tests_properties( [==[Parser - Error Reporting]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[Resolver - Forward Branch]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[Resolver - Forward Branch]==]  )
set_tests_properties( [==[Resolver - Forward Branch]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[Resolver - Backward Branch]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[Resolver - Backward Branch]==]  )
set_tests_properties( [==[Resolver - Backward Branch]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[Resolver - Out of Range]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[Resolver - Out of Range]==]  )
set_tests_properties( [==[Resolver - Out of Range]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[Resolver - Undefined Label]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[Resolver - Undefined Label]==]  )
set_tests_properties( [==[Resolver - Undefined Label]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[System - Load and Execute Simple Program]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[System - Load and Execute Simple Program]==]  )
set_tests_properties( [==[System - Load and Execute Simple Program]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[Loader - File Not Found]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[Loader - File Not Found]==]  )
set_tests_properties( [==[Loader - File Not Found]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[Loader - Empty Data]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[Loader - Empty Data]==]  )
set_tests_properties( [==[Loader - Empty Data]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[Loader - Address Out of Range]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[Loader - Address Out of Range]==]  )
set_tests_properties( [==[Loader - Address Out of Range]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[MemoryMap - Address Validation]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[MemoryMap - Address Validation]==]  )
set_tests_properties( [==[MemoryMap - Address Validation]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[System - ClockIncrements]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[System - ClockIncrements]==]  )
set_tests_properties( [==[System - ClockIncrements]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[System - SystemRun]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[System - SystemRun]==]  )
set_tests_properties( [==[System - SystemRun]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[UART - Address Range Check]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[UART - Address Range Check]==]  )
set_tests_properties( [==[UART - Address Range Check]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[UART - Initial State]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[UART - Initial State]==]  )
set_tests_properties( [==[UART - Initial State]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[UART - Transmit Data]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[UART - Transmit Data]==]  )
set_tests_properties( [==[UART - Transmit Data]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[UART - Receive Data]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[UART - Receive Data]==]  )
set_tests_properties( [==[UART - Receive Data]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[UART - RX IRQ Generation]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[UART - RX IRQ Generation]==]  )
set_tests_properties( [==[UART - RX IRQ Generation]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[UART - TX IRQ Generation]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[UART - TX IRQ Generation]==]  )
set_tests_properties( [==[UART - TX IRQ Generation]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[UART - CONTROL Register Read/Write]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[UART - CONTROL Register Read/Write]==]  )
set_tests_properties( [==[UART - CONTROL Register Read/Write]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[UART - STATUS Register is Read-Only]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[UART - STATUS Register is Read-Only]==]  )
set_tests_properties( [==[UART - STATUS Register is Read-Only]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[UART - Multiple RX Bytes (FIFO behavior)]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[UART - Multiple RX Bytes (FIFO behavior)]==]  )
set_tests_properties( [==[UART - Multiple RX Bytes (FIFO behavior)]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
add_test( [==[UART - Reserved Register Access]==] /home/klea/Documents/Dev/Aurelia/tests/AureliaTests [==[UART - Reserved Register Access]==]  )
set_tests_properties( [==[UART - Reserved Register Access]==] PROPERTIES WORKING_DIRECTORY /home/klea/Documents/Dev/Aurelia/tests)
set( AureliaTests_TESTS [==[Alu - AddBasic]==] [==[Alu - AddZero]==] [==[Alu - AddCarry]==] [==[Alu - SubBorrow]==] [==[Alu - SignedOverflow]==] [==[Lexer - Tokenize Simple Instruction]==] [==[Lexer - Tokenize Immediate Values]==] [==[Lexer - Labels and Directives]==] [==[Lexer - Comments and Whitespace]==] [==[Lexer - Brackets (Memory Access)]==] [==[Lexer - Features: Bin, Neg, Strings]==] [==[Lexer - High Registers]==] [==[Bus - AddressDecoding]==] [==[Bus - ReadOperation]==] [==[Bus - BusFault]==] [==[NvmeController - WriteAndReadBasic]==] [==[BitManip - SetBit]==] [==[BitManip - CheckBit]==] [==[BitManip - ExtractBits]==] [==[CpuPipeline - ExecuteADD]==] [==[CpuPipeline - ExecuteBranch]==] [==[CpuPipeline - ExecuteLDR]==] [==[Cpu - InitialState]==] [==[Cpu - ResetBehavior]==] [==[Cpu - RegisterAccess]==] [==[Decoder - DecodeRegisterArithmetic]==] [==[Decoder - DecodeImmediateMove]==] [==[Decoder - DecodeBranch]==] [==[Encoder - Data Processing]==] [==[Encoder - Immediate Operation]==] [==[Encoder - Memory Operation]==] [==[Encoder - Branch Resolved]==] [==[Encoder - Validation: Wrong Operand Count]==] [==[Encoder - Validation: Wrong Operand Type]==] [==[Encoder - Validation: Immediate Out of Range]==] [==[Encoder - Validation: Memory Operation Wrong Type]==] [==[Encoder - Validation: Branch with Register]==] [==[Encoder - Validation: NOP with Operands]==] [==[Encoder - Validation: CMP Uses Rn Not Rd]==] [==[FTL - Persistence Rebuild]==] [==[FTL - BlockTransitionAndAllocation]==] [==[FTL - DeviceFullBehavior]==] [==[FTL - GarbageCollection_ReclaimsSpace]==] [==[Memory - StorageAccess]==] [==[Memory - LatencySimulation]==] [==[Nand - InitialStateIsErased]==] [==[Nand - ProgramSuccess]==] [==[Nand - ProgramFailure_BitFlipConstraint]==] [==[Nand - EraseRecover]==] [==[Parser - Instruction Parsing]==] [==[Parser - Immediate and Aliases]==] [==[Parser - Memory Operand]==] [==[Parser - String Directive]==] [==[Parser - Error Reporting]==] [==[Resolver - Forward Branch]==] [==[Resolver - Backward Branch]==] [==[Resolver - Out of Range]==] [==[Resolver - Undefined Label]==] [==[System - Load and Execute Simple Program]==] [==[Loader - File Not Found]==] [==[Loader - Empty Data]==] [==[Loader - Address Out of Range]==] [==[MemoryMap - Address Validation]==] [==[System - ClockIncrements]==] [==[System - SystemRun]==] [==[UART - Address Range Check]==] [==[UART - Initial State]==] [==[UART - Transmit Data]==] [==[UART - Receive Data]==] [==[UART - RX IRQ Generation]==] [==[UART - TX IRQ Generation]==] [==[UART - CONTROL Register Read/Write]==] [==[UART - STATUS Register is Read-Only]==] [==[UART - Multiple RX Bytes (FIFO behavior)]==] [==[UART - Reserved Register Access]==])
